-- =============================================================================
-- V1 — Esquema baseline
--
-- Congela el esquema que hasta ahora generaba Hibernate con ddl-auto. A partir
-- de esta migración, `ddl-auto` queda en `validate` y toda la estructura vive
-- en migraciones versionadas.
--
-- Generado desde los metadatos JPA con PostgreSQLDialect y revisado a mano:
--   - nombres de constraint estables (Hibernate generaba hashes tipo FKk8jy62c7...)
--   - índices de claves foránea (PostgreSQL no los crea solos)
--   - índices de las consultas que ya existen en los repositorios
-- =============================================================================

-- ─────────────────────────────── Núcleo ──────────────────────────────────────

CREATE TABLE companies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(31)  NOT NULL,
    company_type VARCHAR(255) NOT NULL CHECK (company_type IN ('ECUADORIAN', 'COLOMBIAN')),
    name         VARCHAR(255) NOT NULL,
    ruc          VARCHAR(20) UNIQUE,
    nit          VARCHAR(20) UNIQUE
);

CREATE TABLE branches (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT       NOT NULL,
    type           VARCHAR(31)  NOT NULL,
    branch_type    VARCHAR(255) NOT NULL CHECK (branch_type IN ('CLINIC', 'HOSPITAL')),
    name           VARCHAR(255) NOT NULL,
    address        VARCHAR(255) NOT NULL,
    has_laboratory BOOLEAN,
    bed_capacity   INTEGER,
    CONSTRAINT fk_branches_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_branches_company ON branches (company_id);

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id        BIGINT,
    branch_id         BIGINT,
    user_type         VARCHAR(31)  NOT NULL,
    first_name        VARCHAR(255) NOT NULL,
    last_name         VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    phone             VARCHAR(255) UNIQUE,
    photo_url         VARCHAR(255),
    auth_provider     VARCHAR(255),
    external_auth_id  VARCHAR(255) UNIQUE,
    document_type     VARCHAR(255) NOT NULL CHECK (document_type IN ('CEDULA_EC', 'RUC_EC', 'CEDULA_CO', 'NIT_CO', 'DNI_PE', 'RUC_PE', 'PASSPORT')),
    document_number   VARCHAR(20),
    passport_number   VARCHAR(30),
    nationality       VARCHAR(100),
    role              VARCHAR(255) NOT NULL CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'DENTIST', 'ASSISTANT', 'RECEPTIONIST', 'EXTERNAL_DOCTOR', 'PATIENT')),
    is_platform_admin BOOLEAN,
    active            BOOLEAN      NOT NULL,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6),
    CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_users_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id)
);

CREATE INDEX idx_users_company ON users (company_id);
CREATE INDEX idx_users_branch  ON users (branch_id);
CREATE INDEX idx_users_role    ON users (role);

-- ──────────────────────── Accesos / RBAC (modules/access) ────────────────────

CREATE TABLE company_memberships (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    company_id BIGINT       NOT NULL,
    role       VARCHAR(255) NOT NULL CHECK (role IN ('SUPER_ADMIN', 'ADMIN', 'DENTIST', 'ASSISTANT', 'RECEPTIONIST', 'EXTERNAL_DOCTOR', 'PATIENT')),
    is_owner   BOOLEAN      NOT NULL,
    active     BOOLEAN      NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_membership_user_company UNIQUE (user_id, company_id),
    CONSTRAINT fk_membership_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_membership_company FOREIGN KEY (company_id) REFERENCES companies (id)
);

CREATE INDEX idx_membership_company ON company_memberships (company_id);

CREATE TABLE membership_branches (
    membership_id BIGINT NOT NULL,
    branch_id     BIGINT NOT NULL,
    PRIMARY KEY (branch_id, membership_id),
    CONSTRAINT fk_membership_branches_membership FOREIGN KEY (membership_id) REFERENCES company_memberships (id),
    CONSTRAINT fk_membership_branches_branch     FOREIGN KEY (branch_id)     REFERENCES branches (id)
);

CREATE TABLE roles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT,
    code       VARCHAR(60)  NOT NULL,
    name       VARCHAR(120) NOT NULL,
    CONSTRAINT uk_role_code_company UNIQUE (code, company_id)
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_permission_code UNIQUE (code)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (permission_id, role_id),
    CONSTRAINT fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    company_id    BIGINT,
    entity_id     BIGINT,
    action        VARCHAR(80) NOT NULL,
    entity_type   VARCHAR(80),
    metadata      VARCHAR(2000),
    created_at    TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_audit_company ON audit_logs (company_id);
CREATE INDEX idx_audit_actor   ON audit_logs (actor_user_id);
CREATE INDEX idx_audit_created ON audit_logs (created_at);

-- ──────────────────────────────── CRM ────────────────────────────────────────

CREATE TABLE crm_contacts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT       NOT NULL,
    branch_id      BIGINT,
    full_name      VARCHAR(150) NOT NULL,
    phone          VARCHAR(30),
    email          VARCHAR(150),
    source_channel VARCHAR(30)  NOT NULL CHECK (source_channel IN ('TELEGRAM', 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK')),
    active         BOOLEAN      NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_crm_contacts_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_crm_contacts_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id)
);

CREATE INDEX idx_crm_contacts_company ON crm_contacts (company_id);
CREATE INDEX idx_crm_contacts_branch  ON crm_contacts (branch_id);

CREATE TABLE crm_contact_phones (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id       BIGINT      NOT NULL,
    company_id       BIGINT      NOT NULL,
    raw_phone        VARCHAR(30) NOT NULL,
    normalized_phone VARCHAR(20) NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_contact_phone_company UNIQUE (normalized_phone, company_id),
    CONSTRAINT fk_crm_contact_phones_contact FOREIGN KEY (contact_id) REFERENCES crm_contacts (id)
);

CREATE INDEX idx_crm_contact_phones_contact ON crm_contact_phones (contact_id);

CREATE TABLE crm_channel_connections (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               BIGINT      NOT NULL,
    branch_id                BIGINT,
    channel_type             VARCHAR(20) NOT NULL CHECK (channel_type IN ('TELEGRAM', 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK')),
    provider                 VARCHAR(20) NOT NULL CHECK (provider IN ('TELEGRAM', 'META')),
    status                   VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'VERIFIED', 'ACTIVE', 'INACTIVE')),
    external_account_id      VARCHAR(100),
    external_phone_number_id VARCHAR(100),
    webhook_verify_token     VARCHAR(150),
    access_token_encrypted   TEXT        NOT NULL,
    webhook_registered_url   TEXT,
    created_at               TIMESTAMP(6) NOT NULL,
    deleted_at               TIMESTAMP(6),
    CONSTRAINT fk_crm_channel_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_crm_channel_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id)
);

-- Resolución de canal operativo en webhooks y envío saliente.
CREATE INDEX idx_crm_channel_company_type_status ON crm_channel_connections (company_id, channel_type, status);
CREATE INDEX idx_crm_channel_phone_number_id     ON crm_channel_connections (external_phone_number_id);
CREATE INDEX idx_crm_channel_verify_token        ON crm_channel_connections (webhook_verify_token);

CREATE TABLE crm_channel_user_links (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id       BIGINT       NOT NULL,
    channel_type     VARCHAR(20)  NOT NULL CHECK (channel_type IN ('TELEGRAM', 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK')),
    external_user_id VARCHAR(100) NOT NULL,
    external_chat_id VARCHAR(100) NOT NULL,
    username         VARCHAR(100),
    display_name     VARCHAR(150),
    created_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_channel_link_contact_channel UNIQUE (contact_id, channel_type),
    CONSTRAINT uk_channel_link_channel_user    UNIQUE (channel_type, external_user_id),
    CONSTRAINT fk_channel_link_contact FOREIGN KEY (contact_id) REFERENCES crm_contacts (id)
);

CREATE TABLE crm_conversations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id            BIGINT      NOT NULL,
    channel_connection_id BIGINT      NOT NULL,
    assigned_user_id      BIGINT,
    status                VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'PENDING', 'CLOSED')),
    last_message_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversations_contact       FOREIGN KEY (contact_id)            REFERENCES crm_contacts (id),
    CONSTRAINT fk_conversations_channel       FOREIGN KEY (channel_connection_id) REFERENCES crm_channel_connections (id),
    CONSTRAINT fk_conversations_assigned_user FOREIGN KEY (assigned_user_id)      REFERENCES users (id)
);

CREATE INDEX idx_conversations_contact_status ON crm_conversations (contact_id, status);
CREATE INDEX idx_conversations_channel        ON crm_conversations (channel_connection_id);
CREATE INDEX idx_conversations_last_message   ON crm_conversations (last_message_at DESC);

CREATE TABLE crm_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id     BIGINT      NOT NULL,
    sent_by_user_id     BIGINT,
    direction           VARCHAR(20) NOT NULL CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    channel_type        VARCHAR(20) NOT NULL CHECK (channel_type IN ('TELEGRAM', 'WHATSAPP', 'INSTAGRAM', 'FACEBOOK')),
    message_type        VARCHAR(20) NOT NULL CHECK (message_type IN ('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'VIDEO', 'VOICE', 'STICKER', 'LOCATION', 'CONTACT', 'TEMPLATE')),
    status              VARCHAR(20) NOT NULL CHECK (status IN ('RECEIVED', 'SENT', 'DELIVERED', 'READ', 'FAILED')),
    external_message_id VARCHAR(120),
    content             TEXT,
    media_url           TEXT,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES crm_conversations (id),
    CONSTRAINT fk_messages_sent_by_user FOREIGN KEY (sent_by_user_id) REFERENCES users (id)
);

CREATE INDEX idx_messages_conversation_created ON crm_messages (conversation_id, created_at);
CREATE INDEX idx_messages_channel_external     ON crm_messages (channel_type, external_message_id);

-- ────────────────────────────── Agendamiento ─────────────────────────────────

CREATE TABLE appointments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      BIGINT       NOT NULL,
    branch_id       BIGINT       NOT NULL,
    contact_id      BIGINT       NOT NULL,
    doctor_id       BIGINT       NOT NULL,
    scheduled_start TIMESTAMP(6) NOT NULL,
    scheduled_end   TIMESTAMP(6) NOT NULL,
    status          VARCHAR(20)  NOT NULL CHECK (status IN ('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'RESCHEDULED')),
    notes           TEXT,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_appointments_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_appointments_branch  FOREIGN KEY (branch_id)  REFERENCES branches (id),
    CONSTRAINT fk_appointments_contact FOREIGN KEY (contact_id) REFERENCES crm_contacts (id),
    CONSTRAINT fk_appointments_doctor  FOREIGN KEY (doctor_id)  REFERENCES users (id)
);

CREATE INDEX idx_appointments_branch_start ON appointments (branch_id, scheduled_start);
CREATE INDEX idx_appointments_doctor_start ON appointments (doctor_id, scheduled_start);
CREATE INDEX idx_appointments_contact      ON appointments (contact_id);

CREATE TABLE branch_schedules (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id             BIGINT      NOT NULL,
    doctor_id             BIGINT      NOT NULL,
    day_of_week           VARCHAR(20) NOT NULL CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    start_time            TIME(6)     NOT NULL,
    end_time              TIME(6)     NOT NULL,
    slot_duration_minutes INTEGER     NOT NULL,
    active                BOOLEAN     NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_branch_schedule_doctor_day UNIQUE (doctor_id, day_of_week),
    CONSTRAINT fk_branch_schedules_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT fk_branch_schedules_doctor FOREIGN KEY (doctor_id) REFERENCES users (id)
);

CREATE INDEX idx_branch_schedules_branch ON branch_schedules (branch_id);

CREATE TABLE branch_blocked_slots (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       BIGINT       NOT NULL,
    start_date_time TIMESTAMP(6) NOT NULL,
    end_date_time   TIMESTAMP(6) NOT NULL,
    reason          VARCHAR(255),
    active          BOOLEAN      NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_blocked_slots_branch FOREIGN KEY (branch_id) REFERENCES branches (id)
);

CREATE INDEX idx_blocked_slots_branch_start ON branch_blocked_slots (branch_id, start_date_time);

CREATE TABLE external_doctor_patient_access (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_doctor_id BIGINT       NOT NULL,
    patient_id         BIGINT       NOT NULL,
    company_id         BIGINT       NOT NULL,
    branch_id          BIGINT,
    appointment_id     BIGINT,
    conversation_id    BIGINT,
    created_by_id      BIGINT,
    reason             VARCHAR(255) NOT NULL,
    active             BOOLEAN      NOT NULL,
    expires_at         TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_ext_doctor_access_doctor     FOREIGN KEY (external_doctor_id) REFERENCES users (id),
    CONSTRAINT fk_ext_doctor_access_created_by FOREIGN KEY (created_by_id)      REFERENCES users (id)
);

CREATE INDEX idx_ext_doctor_access_doctor  ON external_doctor_patient_access (external_doctor_id);
CREATE INDEX idx_ext_doctor_access_patient ON external_doctor_patient_access (patient_id);
